### ISSUE TITLE
GPL Note

### ISSUE THREAD

**Issue by FGDATA** [ACJZA/CSeries#4]
Hi Guys
It would be good if you add a License note to the aircraft. 
(earlier is best)

I've seen aircrafts where the contributors move on/away and years later no-one is able to guarantee that proper licenses are applied.

I understand this material is GPL

Thanks

**Comment by ghost** [comment]
can you then add it, pls? ;-)

---

Gesendet mit der Telekom Mail App
http://www.t-online.de/service/redir/email_app_android_sendmail_footer.htm

--- Original-Nachricht ---
Von: FGDATA
Betreff: [ACJZA/CSeries] GPL Note (#4)
Datum: 25.08.2016, 22:48 Uhr
An: ACJZA/CSeries

Hi Guys
It would be good if you add a License note to the aircraft.
(earlier is best)

I've seen aircrafts where the contributors move on/away and years later 
no-one is able to guarantee that proper licenses are applied.

I understand this material is GPL

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/ACJZA/CSeries/issues/4 , or mute the thread

**Comment by FGDATA** [comment]
Hi @D-ECHO 
Sure, no problem

**Comment by ghost** [comment]
e5081f3 added GPL as in your push request, but I merged manually because of a git problem...
